name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build
        
      - name: Push to Docker Hub Container Registry
        run:  |
          docker tag ${{ secrets.DOCKER_USERNAME }}/framework-tecnocomp-api-mod-admin:latest ${{ secrets.DOCKER_USERNAME }}/framework-tecnocomp-api-mod-admin:${{ github.run_id }}
          
          docker push ${{ secrets.DOCKER_USERNAME }}/framework-tecnocomp-api-mod-admin:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/framework-tecnocomp-api-mod-admin:latest
